### PR TITLE
Update to GitHub CI

### PR DESCRIPTION
**Pull request by guilhermebodin**

### CODE REVIEW

**Comment by guilhermebodin** [comment]
Closes #98

**Comment by joaquimg** [comment]
Awesome!
Just need to update the label on readme.
I would mark x86 as fails allowed. Is it possible?
Cbc and Ipopt might not be super consistent...

**Comment by guilhermebodin** [comment]
I read something about `continue-on-error` but many people said it was catchy, maybe the best thing, for now, is just to remove x86

**Comment by joaquimg** [comment]
fair enough!

**Pull request merged**
