### PR TITLE
Add examples to documentation

### PR DESCRIPTION
**Pull request by odow**
@HesamShaelaie here's an example. You should make other files like `FOBP_example2.jl`. No need to touch the rest.

You can build the docs <s>by installing Julia 1.0</s> as follows:
```
cd BilevelJuMP
julia --project=docs
] instantiate
include("docs/make.jl")
```
Then you can open `docs/build/index.html` locally.

Once this PR is merged, let me know if you want a call to walk through this locally on your machine.

Here's the preview link:

https://joaquimg.github.io/BilevelJuMP.jl/previews/PR121/examples/FOBP_example2/

@joaquimg may need to add you as a collaborator to get the push-preview working. (@joaquimg, you should also protect the master branch to only accept PRs.)

### CODE REVIEW

**Comment by odow** [comment]
Huh. @joaquimg these tests passed?

**Comment by odow** [comment]
@joaquimg I ran into that Cbc SOS bug so I switched to Ipopt. We should probably add a slack integer variable in `Cbc.optimize!` and then delete it after the solve?

**Comment by joaquimg** [comment]
At some point Cbc started failing. That the biggest motivation for me switching to SCIP here.
What exactly do we need to do to solve Cbc issue with SOS1?
SHould we track in an issue?

**Comment by odow** [comment]
It's this: https://github.com/coin-or/Cbc/issues/363

**Comment by joaquimg** [comment]
I see... we need a "slack" binary in the SOS set now.
We could have an option in SOS1Mode to add that binary.
It's hacky but I don't see many other options. And nothing having Cbc is just bad.

**Comment by odow** [comment]
I'll make a PR to Cbc to fix it.

**Pull request merged**
